### ISSUE TITLE
Handle flatten for enums in structs

### ISSUE THREAD

**Issue by wspeirs** [adamreichold/serde-roxmltree#1]
The library does not _seem_ to handle the following scenario:

```rust
#[derive(Deserialize)]
pub enum BarType {
  A(u32),
  B(u64)
}

#[derive(Deserialize)]
pub struct MyType {
  foo: String,
  #[serde(flatten)]
  bar_type: BarType
}
```

As far as I can tell, there is no way to deserialize this type of structure, but it's somewhat common in XML.

**Comment by adamreichold** [comment]
Could you post the XML to go with this so I can better understand how this is supposed to work?

**Comment by wspeirs** [comment]
Sure... I'm trying to parse MS Event Log data which follows this schema: https://gist.github.com/wspeirs/ee20a7e8e612880cb4f5f11b3cf08e4b

The `EvenType` is a sequence of `System` then one-of `EventData`, `UserData`, ... I'm not sure how to go about creating the appropriate struct & enum for this. Here is a sample:

```xml
<?xml version="1.0"?>
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-SPP" Guid="{E23B33B0-C8C9-472C-A5F9-F2BDFEA0F156}" EventSourceName="Software Protection Platform Service"/>
    <EventID Qualifiers="16384">900</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-15T14:18:11.6037830Z"/>
    <EventRecordID>1652</EventRecordID>
    <Correlation/>
    <Execution ProcessID="5204" ThreadID="0"/>
    <Channel>Application</Channel>
    <Computer>test</Computer>
    <Security/>
  </System>
  <EventData>
    <Data>TriggerStarted:6</Data>
  </EventData>
</Event>
```

**Comment by adamreichold** [comment]
It is admittedly not really equivalent because it does not capture the "only one of" aspect, but I think

```rust
#[derive(Deserialize)]
pub struct MyType {
  foo: String,
  A: Option<u32>,
  B: Option<u64>,
}
```

should work, right?

**Comment by wspeirs** [comment]
Yup, that _probably_ would work... but I _think_ the correct way to do this is with `#[serde(flatten)]` on the enum field.

**Comment by adamreichold** [comment]
The problem is that `#[serde(flatten)]` or `#[serde(untagged)]` (which one would use to hoist the `enum` to the top-level) require self-describing formats, i.e. an implementation of the `deserialize_any` method.

I don't think `deserialize_any` can be implemented for this crate though as the XML itself does _not_ define the type (in terms of Serde's data model) which should be passed to the visitor as the same XML can interpreted in multiple ways by using different types which is not the case for e.g. JSON. (This is basically implied by this crate parsing attributes using `FromStr` and enabling to extract both child elements and attributes in a uniform manner.)

EDIT: Add a missing _not_.

**Comment by adamreichold** [comment]
So, I tried whether an incomplete solution might be hand by just assuming some usage in `deserialize_any` like always deserializing a node as a map but that already breaks down if e.g. an enum variant constains a struct with a field mapping to a node because everything inside the flattened enum must be handled using `deserialize_any` and hence a node cannot have two interpretations.

Hence, I fear you will have to rely on having multiple `Option` fields present and manually check which one to use.

**Comment by adamreichold** [comment]
@wspeirs This is not support for `flatten`, but it should enable parsing the above XML without resorting to only optional fields by using the reserved name `#content`, c.f. #6.
